# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(395, 344)
        StartWindow.setMinimumSize(QtCore.QSize(360, 344))
        StartWindow.setMaximumSize(QtCore.QSize(500, 344))
        font = QtGui.QFont()
        font.setPointSize(14)
        StartWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 31, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 31, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 31, 30))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 31, 30))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 31, 30))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(49, 30, 140, 30))
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(49, 60, 140, 30))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(49, 90, 140, 30))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(49, 120, 140, 30))
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(49, 150, 140, 30))
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(49, 180, 140, 30))
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(49, 210, 140, 30))
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 280, 160, 40))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 280, 180, 40))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 250, 340, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 30, 160, 30))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 60, 160, 30))
        self.pushButton_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 90, 160, 30))
        self.pushButton_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 120, 160, 30))
        self.pushButton_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 150, 160, 30))
        self.pushButton_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(220, 180, 160, 30))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 210, 160, 30))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 31, 30))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 31, 30))
        self.label_4.setObjectName("label_4")
        StartWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "CRR model"))
        self.label.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">a</span></p></body></html>"))
        self.label_2.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">b</span></p></body></html>"))
        self.label_3.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">r</span></p></body></html>"))
        self.label_6.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">K</span></p></body></html>"))
        self.label_7.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">N</span></p></body></html>"))
        self.pushButton_4.setText(_translate("StartWindow", "Расчет"))
        self.pushButton_5.setText(_translate("StartWindow", "Ввести данные"))
        self.pushButton_6.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_7.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_8.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_9.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_10.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_11.setText(_translate("StartWindow", "Изменить"))
        self.pushButton_12.setText(_translate("StartWindow", "Изменить"))
        self.label_5.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\">S<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_4.setText(_translate("StartWindow", "<html><head/><body><p align=\"center\">B<span style=\" vertical-align:sub;\">0</span></p></body></html>"))

